trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*
  paths:
    include:
    - '*'
    exclude:
    - README.md
    - docs/*
pr:
  branches:
    include:
    - '*'
  paths:
    include:
    - '*'
    exclude:
    - README.md
    - docs/*

jobs:
- job: aarch64
  pool:
      vmImage: 'macOS-10.14'
  steps:
  - checkout: self
    submodules: true
  - bash: brew install watch gnu-sed
    displayName: Install watch and gnu-sed
  - bash: ci/build_dabnn.sh
    displayName: Build dabnn
  - bash: ci/start_android_emulator.sh
    displayName: Start Android Emulator
  - template: template_dabnn_run_test.yml
  - bash: ci/build_aar.sh
    env: 
      BINTRAY_KEY: $(bintrayKey)
    displayName: Build and Publish AAR package
- job: armv7a_with_NEON
  pool:
      vmImage: 'macOS-10.14'
  steps:
  - checkout: self
    submodules: true
  - bash: brew install watch gnu-sed
    displayName: Install watch and gnu-sed
  - bash: ci/build_dabnn_v7.sh
    displayName: Build dabnn
  - bash: ci/start_android_emulator_v7.sh
    displayName: Start Android Emulator
  - template: template_dabnn_run_test.yml
